import './css/globalcss.css';
import { createApp } from 'vue'

const app = createApp({})

// import { Accordion } from './components/Accordion.vue';
import {default as AnimationSpinner} from './components/AnimationSpinner.vue';
// import {AnimationStatus} from './components/AnimationStatus.vue';
// import {Autocomplete} from './components/Autocomplete.vue';
// import {AutocompleteSelect} from './components/AutocompleteSelect.vue';
// import {Button} from './components/Button.vue';
// import {ButtonCard} from './components/ButtonCard.vue';
// import {ButtonIcon} from './components/ButtonIcon.vue';
// import {Calendar} from './components/Calendar.vue';
// import {Card} from './components/Card.vue';
// import {Context} from './components/Context.vue';
// import {Date} from './components/Date.vue';
// import {Dropdown} from './components/Dropdown.vue';
// import {DropdownFunctional} from './components/DropdownFunctional.vue';
// import {Filedrop} from './components/Filedrop.vue';
// import {Frame} from './components/Frame.vue';
// import {Grid} from './components/Grid.vue';
// import {Hint} from './components/Hint.vue';
// import {HintWrap} from './components/HintWrap.vue';
// import {InputNumberpad} from './components/InputNumberpad.vue';
// import {List} from './components/List.vue';
// import {ListItem} from './components/ListItem.vue';
// import {Logo} from './components/Logo.vue';
// import {Markdown} from './components/Markdown.vue';
// import {OverlayDrawer} from './components/OverlayDrawer.vue';
// import {OverlayDrawerFrame} from './components/OverlayDrawerFrame.vue';
// import {OverlayIndicator} from './components/OverlayIndicator.vue';
// import {OverlayModal} from './components/OverlayModal.vue';
// import {OverlayNotifications} from './components/OverlayNotifications.vue';
// import {Placeholder} from './components/Placeholder.vue';
// import {Quote} from './components/Quote.vue';
// import {RadioGroupBtn} from './components/RadioGroupBtn.vue';
// import {Step} from './components/Step.vue';
// import {Tab} from './components/Tab.vue';
// import {TabContent} from './components/TabContent.vue';
// import {Tag} from './components/Tag.vue';
// import {Toggle} from './components/Toggle.vue';
// import {ToggleMode} from './components/ToggleMode.vue';
// import {TranshesCheckAccordion} from './components/TranshesCheckAccordion.vue';
// import {TransitionExpand} from './components/TransitionExpand.vue';

// app.component('Accordion', Accordion);
app.component('AnimationSpinner', AnimationSpinner);
// app.component('AnimationStatus', AnimationStatus);
// app.component('Autocomplete', Autocomplete);
// app.component('AutocompleteSelect', AutocompleteSelect);
// app.component('Button', Button);
// app.component('ButtonCard', ButtonCard);
// app.component('ButtonIcon', ButtonIcon);
// app.component('Calendar', Calendar);
// app.component('Card', Card);
// app.component('Context', Context);
// app.component('Date', Date);
// app.component('Dropdown', Dropdown);
// app.component('DropdownFunctional', DropdownFunctional);
// app.component('Filedrop', Filedrop);
// app.component('Frame', Frame);
// app.component('Grid', Grid);
// app.component('Hint', Hint);
// app.component('HintWrap', HintWrap);
// app.component('InputNumberpad', InputNumberpad);
// app.component('List', List);
// app.component('ListItem', ListItem);
// app.component('Logo', Logo);
// app.component('Markdown', Markdown);
// app.component('OverlayDrawer', OverlayDrawer);
// app.component('OverlayDrawerFrame', OverlayDrawerFrame);
// app.component('OverlayIndicator', OverlayIndicator);
// app.component('OverlayModal', OverlayModal);
// app.component('OverlayNotifications', OverlayNotifications);
// app.component('Placeholder', Placeholder);
// app.component('Quote', Quote);
// app.component('RadioGroupBtn', RadioGroupBtn);
// app.component('Step', Step);
// app.component('Tab', Tab);
// app.component('TabContent', TabContent);
// app.component('Tag', Tag);
// app.component('Toggle', Toggle);
// app.component('ToggleMode', ToggleMode);
// app.component('TranshesCheckAccordion', TranshesCheckAccordion);
// app.component('TransitionExpand', TransitionExpand);

export { AnimationSpinner };

// Accordion, AnimationSpinner, AnimationStatus, Autocomplete, AutocompleteSelect, Button, ButtonCard, ButtonIcon, Calendar, Card, Context, Date, Dropdown, DropdownFunctional, Filedrop, Frame, Grid, Hint, HintWrap, InputNumberpad, List, ListItem, Logo, Markdown, OverlayDrawer, OverlayDrawerFrame, OverlayIndicator, OverlayModal, OverlayNotifications, Placeholder, Quote, RadioGroupBtn, Step, Tab, TabContent, Tag, Toggle, ToggleMode, TranshesCheckAccordion, TransitionExpand